import Head from "next/head";
import { MockApiForm } from "components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mock api</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <MockApiForm />
      </div>
    </>
  );
}
